// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using IDES.Infrastructure.Persistence;

#nullable disable

namespace IDES.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogueDbContext))]
    [Migration("20251208095220_AjoutFormulesCalculAuxElements")]
    partial class AjoutFormulesCalculAuxElements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("DefinitionElementDefinitionPropriete", b =>
                {
                    b.Property<int>("ProprietesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypesElementsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProprietesId", "TypesElementsId");

                    b.HasIndex("TypesElementsId");

                    b.ToTable("TypeElement_Propriete", (string)null);
                });

            modelBuilder.Entity("IDES.Domain.Catalogue.DefinitionElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesignationTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FormuleAcierHA")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormuleAcierTS")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormuleAvantMetre")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormuleBeton")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormuleCoffrage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrefixeRepere")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TypesElements");
                });

            modelBuilder.Entity("IDES.Domain.Catalogue.DefinitionPropriete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categorie")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomAffichage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeDonnee")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unite")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValeurParDefaut")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Proprietes");
                });

            modelBuilder.Entity("DefinitionElementDefinitionPropriete", b =>
                {
                    b.HasOne("IDES.Domain.Catalogue.DefinitionPropriete", null)
                        .WithMany()
                        .HasForeignKey("ProprietesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IDES.Domain.Catalogue.DefinitionElement", null)
                        .WithMany()
                        .HasForeignKey("TypesElementsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
