// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using IDES.Infrastructure.Persistence;

#nullable disable

namespace IDES.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogueDbContext))]
    [Migration("20251217110201_AjoutTableElementPropriete")]
    partial class AjoutTableElementPropriete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("IDES.Domain.Catalogue.DefinitionElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesignationTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrefixeRepere")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TypesElements");
                });

            modelBuilder.Entity("IDES.Domain.Catalogue.DefinitionPropriete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categorie")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormatAffichage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomAffichage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeDonnee")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unite")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValeurParDefaut")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Proprietes");
                });

            modelBuilder.Entity("IDES.Domain.Catalogue.ElementPropriete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefinitionElementId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefinitionProprieteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Valeur")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionElementId");

                    b.HasIndex("DefinitionProprieteId");

                    b.ToTable("ElementProprietes");
                });

            modelBuilder.Entity("IDES.Domain.Catalogue.ElementPropriete", b =>
                {
                    b.HasOne("IDES.Domain.Catalogue.DefinitionElement", "DefinitionElement")
                        .WithMany("ProprietesAssociees")
                        .HasForeignKey("DefinitionElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IDES.Domain.Catalogue.DefinitionPropriete", "DefinitionPropriete")
                        .WithMany("ElementsAssocies")
                        .HasForeignKey("DefinitionProprieteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefinitionElement");

                    b.Navigation("DefinitionPropriete");
                });

            modelBuilder.Entity("IDES.Domain.Catalogue.DefinitionElement", b =>
                {
                    b.Navigation("ProprietesAssociees");
                });

            modelBuilder.Entity("IDES.Domain.Catalogue.DefinitionPropriete", b =>
                {
                    b.Navigation("ElementsAssocies");
                });
#pragma warning restore 612, 618
        }
    }
}
